// Generated by Flutter tooling during `flutter pub get` / build.
#import "GeneratedPluginRegistrant.h"

@implementation GeneratedPluginRegistrant
+ (void)registerWithRegistry:(NSObject<FlutterPluginRegistry>*)registry {
  // Flutter tooling replaces this with registrations for installed plugins.
}
@end
